# Generated by Django 4.0 on 2021-12-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing_watchlist_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
